# @author Jeffery Russell
#
# Docker-compose script to jupyter lab
# with R, python, and scala kernels
#
# Build:
#   docker-compose build
# Running
#   docker-compose up
#


version: '3'

services:
    jupyterhub:
        build: ./jupyterHub
        ports:
            - "8888:8888"
        volumes:
            - "./notebooks:/home/jovyan/work"
